name: Test Smart Contracts
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "eth/**"
      - ".github/workflows/test-contracts.yml"
  push:
    branches:
      - main
    paths:
      - "eth/**"

jobs:
  test-contracts:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./eth

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: eth/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test

      - name: Run gas report (optional)
        run: REPORT_GAS=true npx hardhat test
        continue-on-error: true

      - name: Run coverage (optional)
        run: npx hardhat coverage
        continue-on-error: true

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: success()
        with:
          file: ./eth/coverage/lcov.info
          flags: smart-contracts
        continue-on-error: true
